apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: foghorn-slack
  namespace: foghorn
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: foghorn-slack
    creationPolicy: Owner
  data:
    - secretKey: SLACK_APP_TOKEN
      remoteRef:
        key: secret/foghorn
        property: slack_app_token
    - secretKey: SLACK_BOT_TOKEN
      remoteRef:
        key: secret/foghorn
        property: slack_bot_token
